# Generated by Django 4.2.9 on 2024-01-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='published_date',
        ),
    ]
